# Generated by Django 4.2.24 on 2025-09-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_class', models.IntegerField()),
                ('tamil_mark', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
        ),
    ]
